"""
Adversarial Training (PGD-AT).

From: Madry et al., "Towards Deep Learning Models Resistant to Adversarial Attacks" (2018).

During training, each mini-batch is augmented with adversarial examples
generated by PGD-7 (7 steps for efficiency). The model learns to be robust
by training on worst-case perturbations.

Tradeoff: clean accuracy drops ~5-8%, but robust accuracy increases significantly.
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader


class AdversarialTrainer:
    """
    PGD-AT training loop.

    Usage:
        trainer = AdversarialTrainer(model, epsilon=0.1, pgd_steps=7)
        for epoch in range(epochs):
            trainer.train_epoch(train_loader, optimizer)
    """

    def __init__(
        self,
        model: nn.Module,
        epsilon: float = 0.1,
        pgd_steps: int = 7,
        step_size: float | None = None,
    ):
        self.model = model
        self.epsilon = epsilon
        self.pgd_steps = pgd_steps
        self.step_size = step_size or (epsilon / 4)

    def train_epoch(
        self, loader: DataLoader, optimizer: torch.optim.Optimizer
    ) -> dict:
        """
        Train one epoch with adversarial examples.

        Returns dict with clean_loss, adv_loss, clean_acc, adv_acc.
        """
        self.model.train()
        total_clean_loss = 0.0
        total_adv_loss = 0.0
        total_clean_correct = 0
        total_adv_correct = 0
        total_samples = 0

        criterion = nn.CrossEntropyLoss()

        for images, labels in loader:
            batch_size = images.shape[0]

            # Generate adversarial examples (PGD-k)
            self.model.eval()
            x_adv = self._pgd_attack(images, labels)
            self.model.train()

            # Forward on adversarial examples
            optimizer.zero_grad()
            adv_logits = self.model(x_adv)
            adv_loss = criterion(adv_logits, labels)
            adv_loss.backward()
            optimizer.step()

            # Track metrics
            with torch.no_grad():
                clean_logits = self.model(images)
                clean_loss = criterion(clean_logits, labels)

                total_clean_loss += clean_loss.item() * batch_size
                total_adv_loss += adv_loss.item() * batch_size
                total_clean_correct += (clean_logits.argmax(1) == labels).sum().item()
                total_adv_correct += (adv_logits.argmax(1) == labels).sum().item()
                total_samples += batch_size

        return {
            "clean_loss": total_clean_loss / total_samples,
            "adv_loss": total_adv_loss / total_samples,
            "clean_acc": total_clean_correct / total_samples,
            "adv_acc": total_adv_correct / total_samples,
        }

    def _pgd_attack(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        """Internal PGD for generating training adversarial examples."""
        x_adv = x.clone().detach()
        x_adv += torch.zeros_like(x).uniform_(-self.epsilon, self.epsilon)
        x_adv = torch.clamp(x_adv, 0.0, 1.0)

        for _ in range(self.pgd_steps):
            x_adv.requires_grad_(True)
            loss = nn.CrossEntropyLoss()(self.model(x_adv), y)
            loss.backward()

            with torch.no_grad():
                x_adv = x_adv + self.step_size * x_adv.grad.sign()
                delta = torch.clamp(x_adv - x, -self.epsilon, self.epsilon)
                x_adv = torch.clamp(x + delta, 0.0, 1.0)

        return x_adv.detach()
