"""
Adversarial Training (PGD-AT).

From: Madry et al., "Towards Deep Learning Models Resistant to Adversarial
Attacks" (2018).

During training, each mini-batch is replaced with adversarial examples
generated by PGD-k (k=7 by default, fewer steps than evaluation for
efficiency). The model minimizes loss on these worst-case perturbations,
approximating the inner-max / outer-min saddle-point objective:

    min_theta  E_(x,y) [ max_{||delta|| <= eps}  L(theta, x + delta, y) ]

Tradeoff: clean accuracy typically drops a few points, while robust
accuracy against first-order attacks rises substantially.
"""

from __future__ import annotations

import torch
import torch.nn as nn
from torch.utils.data import DataLoader


class AdversarialTrainer:
    """
    PGD-AT training loop.

    Args:
        model:      classifier to train (expects inputs in [0, 1]).
        epsilon:    L-inf perturbation budget.
        pgd_steps:  inner PGD steps used to generate training adversarials.
        step_size:  per-step size; defaults to 2.5 * eps / steps, the
                    Madry-style rule that guarantees the ball can be
                    crossed within the step budget.
        device:     device to run on; inferred from the model if omitted.

    Usage:
        trainer = AdversarialTrainer(model, epsilon=0.1, pgd_steps=7)
        history = trainer.train(train_loader, optimizer, epochs=10,
                                test_loader=test_loader)
    """

    def __init__(
        self,
        model: nn.Module,
        epsilon: float = 0.1,
        pgd_steps: int = 7,
        step_size: float | None = None,
        device: torch.device | None = None,
    ):
        self.model = model
        self.epsilon = epsilon
        self.pgd_steps = pgd_steps
        # 2.5 * eps / steps: standard rule so PGD can reach the ball edge.
        self.step_size = step_size or (2.5 * epsilon / pgd_steps)
        self.device = device or next(model.parameters()).device
        self.model.to(self.device)
        self.criterion = nn.CrossEntropyLoss()

    # ------------------------------------------------------------------ #
    # Training
    # ------------------------------------------------------------------ #
    def train(
        self,
        loader: DataLoader,
        optimizer: torch.optim.Optimizer,
        epochs: int,
        test_loader: DataLoader | None = None,
        scheduler: torch.optim.lr_scheduler._LRScheduler | None = None,
        verbose: bool = True,
    ) -> dict[str, list[float]]:
        """
        Run PGD-AT for `epochs` epochs.

        Returns a history dict with per-epoch train metrics, and — if a
        test_loader is given — held-out clean and PGD-robust accuracy.
        """
        history: dict[str, list[float]] = {
            "clean_loss": [], "adv_loss": [],
            "train_clean_acc": [], "train_adv_acc": [],
        }
        if test_loader is not None:
            history["test_clean_acc"] = []
            history["test_robust_acc"] = []

        for epoch in range(1, epochs + 1):
            stats = self.train_epoch(loader, optimizer)
            for key, value in stats.items():
                history[key].append(value)
            if scheduler is not None:
                scheduler.step()

            line = (
                f"epoch {epoch:>3}/{epochs}  "
                f"adv_loss {stats['adv_loss']:.4f}  "
                f"train_clean {stats['train_clean_acc']:.3f}  "
                f"train_adv {stats['train_adv_acc']:.3f}"
            )
            if test_loader is not None:
                clean = self.evaluate_clean(test_loader)
                robust = self.evaluate_robust(test_loader)
                history["test_clean_acc"].append(clean)
                history["test_robust_acc"].append(robust)
                line += f"  | test_clean {clean:.3f}  test_robust {robust:.3f}"
            if verbose:
                print(line)

        return history

    def train_epoch(
        self, loader: DataLoader, optimizer: torch.optim.Optimizer
    ) -> dict[str, float]:
        """Train one epoch on PGD-generated adversarial examples."""
        self.model.train()
        sum_clean_loss = sum_adv_loss = 0.0
        clean_correct = adv_correct = seen = 0

        for images, labels in loader:
            images = images.to(self.device, non_blocking=True)
            labels = labels.to(self.device, non_blocking=True)
            batch = images.shape[0]

            # Inner maximization: craft adversarial examples in eval mode so
            # BatchNorm running stats are not polluted by adversarial inputs.
            was_training = self.model.training
            self.model.eval()
            x_adv = self._pgd_attack(images, labels)
            if was_training:
                self.model.train()

            # Outer minimization: gradient step on the adversarial batch.
            optimizer.zero_grad(set_to_none=True)
            adv_logits = self.model(x_adv)
            adv_loss = self.criterion(adv_logits, labels)
            adv_loss.backward()
            optimizer.step()

            with torch.no_grad():
                clean_logits = self.model(images)
                clean_loss = self.criterion(clean_logits, labels)

                sum_clean_loss += clean_loss.item() * batch
                sum_adv_loss += adv_loss.item() * batch
                clean_correct += (clean_logits.argmax(1) == labels).sum().item()
                adv_correct += (adv_logits.argmax(1) == labels).sum().item()
                seen += batch

        return {
            "clean_loss": sum_clean_loss / seen,
            "adv_loss": sum_adv_loss / seen,
            "train_clean_acc": clean_correct / seen,
            "train_adv_acc": adv_correct / seen,
        }

    # ------------------------------------------------------------------ #
    # Evaluation
    # ------------------------------------------------------------------ #
    @torch.no_grad()
    def evaluate_clean(self, loader: DataLoader) -> float:
        """Clean (unperturbed) accuracy on a held-out loader."""
        self.model.eval()
        correct = seen = 0
        for images, labels in loader:
            images = images.to(self.device)
            labels = labels.to(self.device)
            correct += (self.model(images).argmax(1) == labels).sum().item()
            seen += labels.shape[0]
        return correct / max(seen, 1)

    def evaluate_robust(
        self, loader: DataLoader, pgd_steps: int = 20
    ) -> float:
        """
        Robust accuracy under a PGD-`pgd_steps` attack.

        Uses a stronger attack (more steps) than training, which is the
        standard way to report robustness — evaluating with the same weak
        attack used in training overstates robustness.
        """
        self.model.eval()
        correct = seen = 0
        eval_step = 2.5 * self.epsilon / pgd_steps
        for images, labels in loader:
            images = images.to(self.device)
            labels = labels.to(self.device)
            x_adv = self._pgd_attack(
                images, labels, steps=pgd_steps, step_size=eval_step
            )
            with torch.no_grad():
                preds = self.model(x_adv).argmax(1)
            correct += (preds == labels).sum().item()
            seen += labels.shape[0]
        return correct / max(seen, 1)

    # ------------------------------------------------------------------ #
    # Internal PGD
    # ------------------------------------------------------------------ #
    def _pgd_attack(
        self,
        x: torch.Tensor,
        y: torch.Tensor,
        steps: int | None = None,
        step_size: float | None = None,
    ) -> torch.Tensor:
        """L-inf PGD with random start; used for both training and eval."""
        steps = steps or self.pgd_steps
        step_size = step_size or self.step_size

        x_adv = x.clone().detach()
        x_adv = x_adv + torch.empty_like(x_adv).uniform_(-self.epsilon, self.epsilon)
        x_adv = torch.clamp(x_adv, 0.0, 1.0)

        for _ in range(steps):
            x_adv = x_adv.detach().requires_grad_(True)
            loss = self.criterion(self.model(x_adv), y)
            grad = torch.autograd.grad(loss, x_adv)[0]
            with torch.no_grad():
                x_adv = x_adv + step_size * grad.sign()
                delta = torch.clamp(x_adv - x, -self.epsilon, self.epsilon)
                x_adv = torch.clamp(x + delta, 0.0, 1.0)

        return x_adv.detach()
